<?php
$resolvedTitle = trim((string)($title ?? '')) ?: trim((string)($defaultTitle ?? 'Dashboard')) ?: 'Dashboard';
$userName = (string)(session()->get('name') ?? 'User'); $roleName = ucfirst((string)(session()->get('role') ?? 'user'));
$userPhoto = session()->get('photo'); $photoUrl = (!empty($userPhoto) && file_exists(FCPATH . 'uploads/users/' . $userPhoto)) ? base_url('uploads/users/' . $userPhoto) : 'https://ui-avatars.com/api/?name=' . urlencode($userName);
$notifCount = (int)($notifCount ?? 0); $notifications = $notifications ?? []; $notifBadge = $notifCount > 99 ? '99+' : (string)$notifCount;
?>
<nav class="app-header navbar navbar-expand border-bottom"><div class="container-fluid d-flex align-items-center app-header-inner"><div class="d-flex align-items-center header-left-controls"><button class="btn btn-link header-sidebar-toggle header-icon-btn" data-lte-toggle="sidebar" aria-label="Buka tutup sidebar"><i class="bi bi-list"></i></button><div class="app-header-title"><span class="fw-semibold fs-5 header-title-text"><?= esc($resolvedTitle) ?></span></div></div>
<ul class="navbar-nav ms-auto align-items-center flex-row header-right-controls"><li class="nav-item me-2"><button id="theme-toggle" type="button" class="theme-toggle" aria-label="Ganti tema" title="Ganti tema"><i class="bi bi-moon-stars"></i></button></li>
<li class="nav-item dropdown header-notif-item me-1"><a class="nav-link position-relative header-notif-toggle" data-bs-toggle="dropdown" href="#" aria-label="Notifikasi"><i class="bi bi-bell fs-5"></i><?php if ($notifCount > 0): ?><span class="position-absolute badge bg-danger rounded-pill header-notif-badge"><?= esc($notifBadge) ?></span><?php endif; ?></a><ul class="dropdown-menu dropdown-menu-end shadow-sm header-notif-menu"><li class="dropdown-header header-notif-head d-flex align-items-center justify-content-between"><span class="d-inline-flex align-items-center gap-2"><span class="header-menu-icon"><i class="bi bi-bell"></i></span>Notifikasi</span><span class="badge bg-primary-subtle text-primary-emphasis rounded-pill"><?= $notifCount ?></span></li><li><hr class="dropdown-divider"></li>
<?php if ($notifications): ?><?php foreach ($notifications as $notif): ?><li><a href="<?= esc($notif['url'] ?? base_url('home')) ?>" class="dropdown-item header-menu-item"><span class="header-menu-item-icon"><i class="<?= esc($notif['icon'] ?? 'bi bi-info-circle text-primary') ?>"></i></span><span class="header-menu-item-text"><?= esc($notif['text'] ?? '-') ?></span></a></li><?php endforeach; ?><?php else: ?><li class="px-3 py-3 text-center text-muted small"><i class="bi bi-bell-slash d-block mb-1 fs-5"></i>Tidak ada notifikasi</li><?php endif; ?><li><hr class="dropdown-divider"></li><li><a href="<?= base_url('home?view=notifications') ?>" class="dropdown-item text-center small fw-semibold text-primary">Lihat semua notifikasi</a></li></ul></li>
<li class="nav-item dropdown header-profile-item ms-1"><a class="nav-link dropdown-toggle d-flex align-items-center justify-content-center header-profile-toggle" data-bs-toggle="dropdown" href="#" aria-label="Menu pengguna"><img class="rounded-circle header-profile-avatar" width="32" height="32" src="<?= esc($photoUrl) ?>" alt="Profile"></a><ul class="dropdown-menu dropdown-menu-end shadow header-profile-menu"><li class="dropdown-header header-profile-head d-flex align-items-center gap-2"><img class="rounded-circle header-profile-avatar" width="42" height="42" src="<?= esc($photoUrl) ?>" alt="Profile"><div><div class="fw-semibold"><?= esc($userName) ?></div><div class="small text-muted">Peran: <?= esc($roleName) ?></div></div></li><li><hr class="dropdown-divider"></li><li><a class="dropdown-item" href="<?= base_url('settings?section=user') ?>"><i class="bi bi-gear me-2"></i>Pengaturan User</a></li><?php if (hasRole(['admin','compliance'])): ?><li><a class="dropdown-item" href="<?= base_url('settings?section=company') ?>"><i class="bi bi-buildings me-2"></i>Pengaturan Perusahaan</a></li><?php endif; ?><li><hr class="dropdown-divider"></li><li><a class="dropdown-item text-danger" href="<?= base_url('logout') ?>"><i class="bi bi-box-arrow-right me-2"></i>Keluar</a></li></ul></li></ul></div></nav>
